[versions]
gradle-plugin = "8.4.1"
java = "17"
kotlin = "1.9.22"
bouncy-castle = "1.78.1"
gson = "2.9.1"

[libraries]
bcprov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncy-castle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

[plugins]
android-library = { id = "com.android.library", version.ref = "gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }